/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  AMBBridgeHelper,
  AMBBridgeHelperInterface,
} from "../AMBBridgeHelper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_homeBridge",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "AMBcontract",
    outputs: [
      {
        internalType: "contract IHomeBridge",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "clean",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_message",
        type: "bytes",
      },
    ],
    name: "getSignatures",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AMBBridgeHelper__factory {
  static readonly abi = _abi;
  static createInterface(): AMBBridgeHelperInterface {
    return new utils.Interface(_abi) as AMBBridgeHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AMBBridgeHelper {
    return new Contract(address, _abi, signerOrProvider) as AMBBridgeHelper;
  }
}
