/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface Erc20ToNativeBridgeHelperInterface extends utils.Interface {
  functions: {
    "getMessage(bytes32)": FunctionFragment;
    "getMessageHash(address,uint256,bytes32)": FunctionFragment;
    "getMessageHash(address,uint256,bytes32,address)": FunctionFragment;
    "foreignBridge()": FunctionFragment;
    "owner()": FunctionFragment;
    "getSignatures(bytes32)": FunctionFragment;
    "bridge()": FunctionFragment;
    "clean()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getMessage"
      | "getMessageHash(address,uint256,bytes32)"
      | "getMessageHash(address,uint256,bytes32,address)"
      | "foreignBridge"
      | "owner"
      | "getSignatures"
      | "bridge"
      | "clean"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMessage",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageHash(address,uint256,bytes32)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageHash(address,uint256,bytes32,address)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "foreignBridge",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSignatures",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "bridge", values?: undefined): string;
  encodeFunctionData(functionFragment: "clean", values?: undefined): string;

  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMessageHash(address,uint256,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageHash(address,uint256,bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "foreignBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clean", data: BytesLike): Result;

  events: {};
}

export interface Erc20ToNativeBridgeHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Erc20ToNativeBridgeHelperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getMessage(
      _msgHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { result: string }>;

    "getMessageHash(address,uint256,bytes32)"(
      _recipient: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _origTxHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getMessageHash(address,uint256,bytes32,address)"(
      _recipient: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    foreignBridge(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    getSignatures(
      _msgHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bridge(overrides?: CallOverrides): Promise<[string]>;

    clean(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getMessage(
    _msgHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  "getMessageHash(address,uint256,bytes32)"(
    _recipient: PromiseOrValue<string>,
    _value: PromiseOrValue<BigNumberish>,
    _origTxHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  "getMessageHash(address,uint256,bytes32,address)"(
    _recipient: PromiseOrValue<string>,
    _value: PromiseOrValue<BigNumberish>,
    _nonce: PromiseOrValue<BytesLike>,
    _token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  foreignBridge(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  getSignatures(
    _msgHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  bridge(overrides?: CallOverrides): Promise<string>;

  clean(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getMessage(
      _msgHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "getMessageHash(address,uint256,bytes32)"(
      _recipient: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _origTxHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "getMessageHash(address,uint256,bytes32,address)"(
      _recipient: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    foreignBridge(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    getSignatures(
      _msgHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    bridge(overrides?: CallOverrides): Promise<string>;

    clean(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getMessage(
      _msgHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMessageHash(address,uint256,bytes32)"(
      _recipient: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _origTxHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMessageHash(address,uint256,bytes32,address)"(
      _recipient: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    foreignBridge(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    getSignatures(
      _msgHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bridge(overrides?: CallOverrides): Promise<BigNumber>;

    clean(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getMessage(
      _msgHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getMessageHash(address,uint256,bytes32)"(
      _recipient: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _origTxHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getMessageHash(address,uint256,bytes32,address)"(
      _recipient: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    foreignBridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSignatures(
      _msgHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    clean(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
