/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from './common'

export interface OmniBridgeFeeManagerInterface extends utils.Interface {
  functions: {
    'FOREIGN_TO_HOME_FEE()': FunctionFragment
    'HOME_TO_FOREIGN_FEE()': FunctionFragment
    'addRewardAddress(address)': FunctionFragment
    'calculateFee(bytes32,address,uint256)': FunctionFragment
    'distributeFee(address)': FunctionFragment
    'getFee(bytes32,address)': FunctionFragment
    'getModuleInterfacesVersion()': FunctionFragment
    'isRewardAddress(address)': FunctionFragment
    'mediator()': FunctionFragment
    'owner()': FunctionFragment
    'removeRewardAddress(address)': FunctionFragment
    'rewardAddressCount()': FunctionFragment
    'rewardAddressList()': FunctionFragment
    'setFee(bytes32,address,uint256)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'FOREIGN_TO_HOME_FEE'
      | 'HOME_TO_FOREIGN_FEE'
      | 'addRewardAddress'
      | 'calculateFee'
      | 'distributeFee'
      | 'getFee'
      | 'getModuleInterfacesVersion'
      | 'isRewardAddress'
      | 'mediator'
      | 'owner'
      | 'removeRewardAddress'
      | 'rewardAddressCount'
      | 'rewardAddressList'
      | 'setFee'
      | 'transferOwnership',
  ): FunctionFragment

  encodeFunctionData(functionFragment: 'FOREIGN_TO_HOME_FEE', values?: undefined): string
  encodeFunctionData(functionFragment: 'HOME_TO_FOREIGN_FEE', values?: undefined): string
  encodeFunctionData(functionFragment: 'addRewardAddress', values: [PromiseOrValue<string>]): string
  encodeFunctionData(
    functionFragment: 'calculateFee',
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string
  encodeFunctionData(functionFragment: 'distributeFee', values: [PromiseOrValue<string>]): string
  encodeFunctionData(
    functionFragment: 'getFee',
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>],
  ): string
  encodeFunctionData(functionFragment: 'getModuleInterfacesVersion', values?: undefined): string
  encodeFunctionData(functionFragment: 'isRewardAddress', values: [PromiseOrValue<string>]): string
  encodeFunctionData(functionFragment: 'mediator', values?: undefined): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'removeRewardAddress',
    values: [PromiseOrValue<string>],
  ): string
  encodeFunctionData(functionFragment: 'rewardAddressCount', values?: undefined): string
  encodeFunctionData(functionFragment: 'rewardAddressList', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'setFee',
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [PromiseOrValue<string>],
  ): string

  decodeFunctionResult(functionFragment: 'FOREIGN_TO_HOME_FEE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'HOME_TO_FOREIGN_FEE', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'addRewardAddress', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'calculateFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'distributeFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getModuleInterfacesVersion', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'isRewardAddress', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'mediator', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'removeRewardAddress', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'rewardAddressCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'rewardAddressList', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'setFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result

  events: {
    'FeeUpdated(bytes32,address,uint256)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'FeeUpdated'): EventFragment
}

export interface FeeUpdatedEventObject {
  feeType: string
  token: string
  fee: BigNumber
}
export type FeeUpdatedEvent = TypedEvent<[string, string, BigNumber], FeeUpdatedEventObject>

export type FeeUpdatedEventFilter = TypedEventFilter<FeeUpdatedEvent>

export interface OmniBridgeFeeManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: OmniBridgeFeeManagerInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    FOREIGN_TO_HOME_FEE(overrides?: CallOverrides): Promise<[string]>

    HOME_TO_FOREIGN_FEE(overrides?: CallOverrides): Promise<[string]>

    addRewardAddress(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    calculateFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>

    distributeFee(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    getFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>

    getModuleInterfacesVersion(overrides?: CallOverrides): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        major: BigNumber
        minor: BigNumber
        patch: BigNumber
      }
    >

    isRewardAddress(_addr: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[boolean]>

    mediator(overrides?: CallOverrides): Promise<[string]>

    owner(overrides?: CallOverrides): Promise<[string]>

    removeRewardAddress(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    rewardAddressCount(overrides?: CallOverrides): Promise<[BigNumber]>

    rewardAddressList(overrides?: CallOverrides): Promise<[string[]]>

    setFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>
  }

  FOREIGN_TO_HOME_FEE(overrides?: CallOverrides): Promise<string>

  HOME_TO_FOREIGN_FEE(overrides?: CallOverrides): Promise<string>

  addRewardAddress(
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  calculateFee(
    _feeType: PromiseOrValue<BytesLike>,
    _token: PromiseOrValue<string>,
    _value: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>

  distributeFee(
    _token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  getFee(
    _feeType: PromiseOrValue<BytesLike>,
    _token: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<BigNumber>

  getModuleInterfacesVersion(overrides?: CallOverrides): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      major: BigNumber
      minor: BigNumber
      patch: BigNumber
    }
  >

  isRewardAddress(_addr: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>

  mediator(overrides?: CallOverrides): Promise<string>

  owner(overrides?: CallOverrides): Promise<string>

  removeRewardAddress(
    _addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  rewardAddressCount(overrides?: CallOverrides): Promise<BigNumber>

  rewardAddressList(overrides?: CallOverrides): Promise<string[]>

  setFee(
    _feeType: PromiseOrValue<BytesLike>,
    _token: PromiseOrValue<string>,
    _fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  transferOwnership(
    _newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  callStatic: {
    FOREIGN_TO_HOME_FEE(overrides?: CallOverrides): Promise<string>

    HOME_TO_FOREIGN_FEE(overrides?: CallOverrides): Promise<string>

    addRewardAddress(_addr: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>

    calculateFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    distributeFee(_token: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>

    getFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getModuleInterfacesVersion(overrides?: CallOverrides): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        major: BigNumber
        minor: BigNumber
        patch: BigNumber
      }
    >

    isRewardAddress(_addr: PromiseOrValue<string>, overrides?: CallOverrides): Promise<boolean>

    mediator(overrides?: CallOverrides): Promise<string>

    owner(overrides?: CallOverrides): Promise<string>

    removeRewardAddress(_addr: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>

    rewardAddressCount(overrides?: CallOverrides): Promise<BigNumber>

    rewardAddressList(overrides?: CallOverrides): Promise<string[]>

    setFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<void>

    transferOwnership(_newOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>
  }

  filters: {
    'FeeUpdated(bytes32,address,uint256)'(
      feeType?: null,
      token?: PromiseOrValue<string> | null,
      fee?: null,
    ): FeeUpdatedEventFilter
    FeeUpdated(
      feeType?: null,
      token?: PromiseOrValue<string> | null,
      fee?: null,
    ): FeeUpdatedEventFilter
  }

  estimateGas: {
    FOREIGN_TO_HOME_FEE(overrides?: CallOverrides): Promise<BigNumber>

    HOME_TO_FOREIGN_FEE(overrides?: CallOverrides): Promise<BigNumber>

    addRewardAddress(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    calculateFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    distributeFee(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    getFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getModuleInterfacesVersion(overrides?: CallOverrides): Promise<BigNumber>

    isRewardAddress(_addr: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>

    mediator(overrides?: CallOverrides): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    removeRewardAddress(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    rewardAddressCount(overrides?: CallOverrides): Promise<BigNumber>

    rewardAddressList(overrides?: CallOverrides): Promise<BigNumber>

    setFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>
  }

  populateTransaction: {
    FOREIGN_TO_HOME_FEE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    HOME_TO_FOREIGN_FEE(overrides?: CallOverrides): Promise<PopulatedTransaction>

    addRewardAddress(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    calculateFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      _value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    distributeFee(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    getFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getModuleInterfacesVersion(overrides?: CallOverrides): Promise<PopulatedTransaction>

    isRewardAddress(
      _addr: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    mediator(overrides?: CallOverrides): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    removeRewardAddress(
      _addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    rewardAddressCount(overrides?: CallOverrides): Promise<PopulatedTransaction>

    rewardAddressList(overrides?: CallOverrides): Promise<PopulatedTransaction>

    setFee(
      _feeType: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>
  }
}
