/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from './common'

export interface USDSdepositInterface extends utils.Interface {
  functions: {
    'relayTokens(address)': FunctionFragment
    'xDAIBridge()': FunctionFragment
  }

  getFunction(nameOrSignatureOrTopic: 'relayTokens' | 'xDAIBridge'): FunctionFragment

  encodeFunctionData(functionFragment: 'relayTokens', values: [PromiseOrValue<string>]): string
  encodeFunctionData(functionFragment: 'xDAIBridge', values?: undefined): string

  decodeFunctionResult(functionFragment: 'relayTokens', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'xDAIBridge', data: BytesLike): Result

  events: {}
}

export interface USDSdeposit extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: USDSdepositInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    relayTokens(
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>

    xDAIBridge(overrides?: CallOverrides): Promise<[string]>
  }

  relayTokens(
    recipient: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>

  xDAIBridge(overrides?: CallOverrides): Promise<string>

  callStatic: {
    relayTokens(recipient: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>

    xDAIBridge(overrides?: CallOverrides): Promise<string>
  }

  filters: {}

  estimateGas: {
    relayTokens(
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>

    xDAIBridge(overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    relayTokens(
      recipient: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>

    xDAIBridge(overrides?: CallOverrides): Promise<PopulatedTransaction>
  }
}
