import { formatUnits } from 'viem'

/**
 * Convert a raw on-chain amount (`bigint`, in the token's smallest unit) into a
 * human-readable JS number, using the token's `decimals`.
 *
 * Display-only: `parseFloat` narrows to float64, so use this at the render
 * boundary. Keep amounts as `bigint` for any exact / threshold math upstream.
 */
export const formatUnitsToNumber = (value: bigint, decimals: number): number =>
  parseFloat(formatUnits(value, decimals))

export const fixedNumber = (amount: number, decimalsRound: number) => {
  const decimalsPow = Math.pow(10, decimalsRound) // For n decimals, multiply and divide by 10^n
  const roundedAmount = amount + Number.EPSILON // to evade rounding issues generated by toFixed method
  const result = Math.round(roundedAmount * decimalsPow) / decimalsPow
  return result
}

export const percentageNumber = (amount: number, total: number) => {
  const percentage = (amount / total) * 100
  const result = fixedNumber(percentage, 1)
  return result
}
