export const fixedNumber = (amount: number, decimalsRound: number) => {
  const decimalsPow = Math.pow(10, decimalsRound) // For n decimals, multiply and divide by 10^n
  const roundedAmount = amount + Number.EPSILON // to evade rounding issues generated by toFixed method
  const result = Math.round(roundedAmount * decimalsPow) / decimalsPow
  return result
}

export const percentageNumber = (amount: number, total: number) => {
  const percentage = (amount / total) * 100
  const result = fixedNumber(percentage, 1)
  return result
}
