export default [
  {
    constant: true,
    inputs: [{ name: '_msgHash', type: 'bytes32' }],
    name: 'getMessage',
    outputs: [{ name: 'result', type: 'bytes' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [
      { name: '_recipient', type: 'address' },
      { name: '_value', type: 'uint256' },
      { name: '_origTxHash', type: 'bytes32' },
    ],
    name: 'getMessageHash',
    outputs: [{ name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'foreignBridge',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [{ name: '_msgHash', type: 'bytes32' }],
    name: 'getSignatures',
    outputs: [{ name: '', type: 'bytes' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [
      { name: '_recipient', type: 'address' },
      { name: '_value', type: 'uint256' },
      { name: '_nonce', type: 'bytes32' },
      { name: '_token', type: 'address' },
    ],
    name: 'getMessageHash',
    outputs: [{ name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: true,
    inputs: [],
    name: 'bridge',
    outputs: [{ name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
  },
  {
    constant: false,
    inputs: [],
    name: 'clean',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { name: '_homeBridge', type: 'address' },
      { name: '_foreignBridge', type: 'address' },
    ],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
] as const
