# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: gnosis-bridge-indexer
unordered_multichain_mode: false
preload_handlers: true
raw_events: true

networks:
# [Home] (Gnosis)
- id: 100
  # rpc_config:
  #   url: ${ENVIO_RPC_HOME}
  start_block: 7904944
  contracts:
  - name: XDAIHome
    address:
    - 0x7301CFA0e1756B71869E93d4e4Dca5c7d0eb0AA6
    start_block: 39567805
    handler: src/eventHandlers/XDAI/index.ts
    events:
    # [XDAI Home -> Foreign]
    # [1. Init]
      # Before Hashi update
    - event: UserRequestForSignature(address recipient, uint256 value)
      name: UserRequestForSignature_NoNonceNoToken
      field_selection:
        transaction_fields:
          - "hash"
          - "from"
      # After Hashi update
    - event: UserRequestForSignature(address recipient, uint256 value, bytes32 nonce)
      name: UserRequestForSignature_WithNonceNoToken
      field_selection:
        transaction_fields:
          - "hash"
          - "from"
      # After USDS migration (current version)
    - event: UserRequestForSignature(address recipient, uint256 value, bytes32 nonce, address token)
      name: UserRequestForSignature
      field_selection:
        transaction_fields:
          - "hash"
          - "from"

    # [XDAI Home -> Foreign]
    # [2. Validation]
    - event: SignedForUserRequest(address indexed signer, bytes32 messageHash)
      field_selection:
        transaction_fields:
          - "hash"

    # [XDAI Home -> Foreign]
    # [3. Ready to execute on Foreign (treshold signatures reached)]
    - event: CollectedSignatures(address authorityResponsibleForRelay, bytes32 messageHash, uint256 NumberOfCollectedSignatures)
      field_selection:
        transaction_fields:
          - "hash"
    
    # [XDAI Foreign -> Home]
    # [2. Validation]
    - event: SignedForAffirmation(address indexed signer, bytes32 nonce)
      field_selection:
        transaction_fields:
          - "hash"

    # [XDAI Foreign -> Home]
    # [3. Execution]
    - event: AffirmationCompleted(address recipient, uint256 value, bytes32 nonce)
      field_selection:
        transaction_fields:
          - "hash"
          - "from"

  - name: AMBHome
    address:
    - 0x75Df5AF045d91108662D8080fD1FEFAd6aA0bb59
    start_block: 39567805
    handler: src/eventHandlers/AMB/index.ts
    events:
    # [AMB Home -> Foreign]
    # [1. Init]
    - event: UserRequestForSignature(bytes32 indexed messageId, bytes encodedData)
      field_selection:
        transaction_fields:
          - "hash"

    # [AMB Home -> Foreign]
    # [2. Validation]
    - event: SignedForUserRequest(address indexed signer, bytes32 messageHash)
      field_selection:
        transaction_fields:
          - "hash"

    # [AMB Home -> Foreign]
    # [3. Ready to execute on Foreign (treshold signatures reached)]
    - event: CollectedSignatures(address authorityResponsibleForRelay, bytes32 messageHash, uint256 NumberOfCollectedSignatures)
      field_selection:
        transaction_fields:
          - "hash"

    # [AMB Foreign -> Home]
    # [2. Validation]
    - event: SignedForAffirmation(address indexed signer, bytes32 messageHash)
      field_selection:
        transaction_fields:
          - "hash"

    # [AMB Foreign -> Home]
    # [3. Execution]
    - event: AffirmationCompleted(address indexed sender, address indexed executor, bytes32 indexed messageId, bool status)
      field_selection:
        transaction_fields:
          - "hash"
          - "from"

  # OmniBridge Mediators on Gnosis Chain (Home)
  - name: OmniBridgeHomeMediator
    address:
    - 0xf6A78083ca3e2a662D6dd1703c939c8aCE2e268d
    - 0xbed794745e2a0543ee609795ade87a55bbe935ba
    - 0xf75c28fe07e0647b05160288f172ad27cccd8f30
    - 0x0eeacdb0dd96588711581c5f3173dd55841b8e91
    - 0x53f3f44c434494da73ec44a6e8a8d091332bc2ce
    - 0x7d55f9981d4e10a193314e001b96f72fcc901e40
    - 0xbe20f60339b06db32c319d46cf3bc9bacc0694ab
    - 0x68a64df7458a8eb2677991e657508fe00205332d
    - 0x5f0fe58709639a39c193521d919afaef02e570f7
    start_block: 39567805
    handler: src/eventHandlers/AMB/index.ts
    events:
    - event: TokensBridgingInitiated(address indexed token, address indexed sender, uint256 value, bytes32 indexed messageId)
    - event: TokensBridged(address indexed token, address indexed recipient, uint256 value, bytes32 indexed messageId)

  - name: XDAIBridgeValidators
    address:
    - 0xB289f0e6fBDFf8EEE340498a56e1787B303F1B6D
    start_block: 7904944
    handler: src/eventHandlers/validator.ts
    events:
    - event: ValidatorAdded(address indexed validator)
      field_selection:
        transaction_fields:
          - "hash"
    - event: ValidatorRemoved(address indexed validator)
      field_selection:
        transaction_fields:
          - "hash"

  - name: AMBBridgeValidators
    address:
    - 0xA280feD8D7CaD9a76C8b50cA5c33c2534fFa5008
    start_block: 7904944
    handler: src/eventHandlers/validator.ts
    events:
    - event: ValidatorAdded(address indexed validator)
      field_selection:
        transaction_fields:
          - "hash"
    - event: ValidatorRemoved(address indexed validator)
      field_selection:
        transaction_fields:
          - "hash"


# [Foreign] (Ethereum)
- id: 1
  # rpc_config:
  #   url: ${ENVIO_RPC_FOREIGN}
  start_block: 22272590
  contracts:

  # [XDAI Foreign -> Home]
  # [0. Token transfer] (DAI transferred to the bridge contract)
  - name: DAI
    address:
    - 0x6B175474E89094C44Da98b954EedeAC495271d0F
    handler: src/eventHandlers/XDAI/index.ts
    events:
    - event: Transfer(address indexed from, address indexed to, uint256 value)
      field_selection:
        transaction_fields:
          - "hash"
  # [0. Token transfer] (USDS transferred to the bridge contract)
  - name: USDS
    address:
    - 0xdC035D45d973E3EC169d2276DDab16f1e407384F
    handler: src/eventHandlers/XDAI/index.ts
    events:
    - event: Transfer(address indexed from, address indexed to, uint256 value)
      field_selection:
        transaction_fields:
          - "hash"

  - name: XDAIForeign
    address:
    - 0x4aa42145Aa6Ebf72e164C9bBC74fbD3788045016
    handler: src/eventHandlers/XDAI/index.ts
    events:
    # [XDAI Home -> Foreign]
    # [4. Execution (token claimed)]
    - event: RelayedMessage(address recipient, uint256 value, bytes32 transactionHash)
      field_selection:
        transaction_fields:
          - "hash"
          - "from"

    # [XDAI Foreign -> Home]
    # [1. Init]
      # Before Hashi update
    - event: UserRequestForAffirmation(address recipient, uint256 value)
      name: UserRequestForAffirmation_NoNonce
      field_selection:
        transaction_fields:
          - "hash"
      # After Hashi update (current version)
    - event: UserRequestForAffirmation(address recipient, uint256 value, bytes32 nonce)
      name: UserRequestForAffirmation
      field_selection:
        transaction_fields:
          - "hash"

  - name: AMBForeign
    address:
    - 0x4C36d2919e407f0Cc2Ee3c993ccF8ac26d9CE64e
    handler: src/eventHandlers/AMB/index.ts
    events:
    # [AMB Home -> Foreign]
    # [4. Execution (token claimed)]
    - event: RelayedMessage(address indexed sender, address indexed executor, bytes32 indexed messageId, bool status)
      field_selection:
        transaction_fields:
          - "hash"
          - "from"

    # [AMB Foreign -> Home]
    # [1. Init]
    - event: UserRequestForAffirmation(bytes32 indexed messageId, bytes encodedData)
      field_selection:
        transaction_fields:
          - "hash"

  # OmniBridge Mediators on Ethereum (Foreign)
  - name: OmniBridgeForeignMediator
    address:
    - 0x88ad09518695c6c3712AC10a214bE5109a655671
    - 0xed7e6720ac8525ac1aeee710f08789d02cd87ecb
    - 0xe7228b4ebad37ba031a8b63473727f991e262dcd
    - 0x81a4833b3a40e7c61efe9d1a287343797993b1e8
    - 0x29e572d45cc33d5a68dcc8f92bfc7ded0017bc59
    - 0x2eeeddeece91c9f4c5ba4c8e1d784a0234c6d015
    - 0x5689c65cfe5e8bf1a5f836c956dea1b3b8be00bb
    - 0xe964a36142bbe39751d0b4d6140fc0b8c48e68be
    - 0x41a4ee2855a7dc328524babb07d7f505b201133e
    handler: src/eventHandlers/AMB/index.ts
    events:
    - event: TokensBridgingInitiated(address indexed token, address indexed sender, uint256 value, bytes32 indexed messageId)
    - event: TokensBridged(address indexed token, address indexed recipient, uint256 value, bytes32 indexed messageId)

